execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=64..80] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.01
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=60..64] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.02
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=56..60] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.03
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=52..56] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.04
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=48..52] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.05
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=44..48] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.06
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=40..44] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.07
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=36..40] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.08
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=32..36] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.09
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=28..32] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.12
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=24..28] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.25
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=20..24] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.5
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=16..20] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^1
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=12..16] at @s positioned as @s facing entity @e[tag=blackhole] eyes run tp @s ^ ^ ^2
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=8..12] at @s positioned as @s facing entity @e[tag=blackhole] eyes run tp @s ^ ^ ^4
execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!player,type=!item,distance=2..8] at @s positioned as @s facing entity @e[tag=blackhole] eyes run tp @s ^ ^ ^2

execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=64..80] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.01
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=60..64] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.02
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=56..60] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.03
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=52..56] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.04
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=48..52] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.05
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=44..48] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.06
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=40..44] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.07
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=36..40] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.08
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=32..36] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.09
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=28..32] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.12
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=24..28] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.25
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=20..24] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^0.5
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=16..20] at @s positioned as @s facing entity @e[tag=blackhole] eyes if block ^ ^ ^0.6 #expertmodecore:air run tp @s ^ ^ ^1
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=12..16] at @s positioned as @s facing entity @e[tag=blackhole] eyes run tp @s ^ ^ ^2
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=8..12] at @s positioned as @s facing entity @e[tag=blackhole] eyes run tp @s ^ ^ ^4
execute at @e[tag=blackhole] run execute as @a[gamemode=!creative,gamemode=!spectator,distance=2..8] at @s positioned as @s facing entity @e[tag=blackhole] eyes run tp @s ^ ^ ^2

execute at @e[tag=blackhole] run execute as @e[type=!item_frame,type=!painting,type=!armor_stand,type=!tnt,distance=0..2] at @s if entity @e[tag=blackhole,distance=0..2] run kill @s
# execute at @e[tag=blackhole] run execute as @e[type=tnt,distance=0..2] at @s if entity @e[tag=blackhole,distance=0..2] run teleport @s @e[tag=blackhole,distance=0..2,limit=1]
# execute at @e[tag=blackhole] run execute as @e[type=tnt,distance=0..2,nbt={Fuse:1s}] at @s if entity @e[tag=blackhole,distance=0..2] run kill @e[tag=blackhole,distance=0..2,limit=1]

execute at @e[tag=blackhole] run execute as @e[type=item,distance=10..80] at @s positioned as @s facing entity @e[tag=blackhole] eyes run tp @s ^ ^ ^0.05
execute at @e[tag=blackhole] run execute as @e[type=item,distance=..10] run kill @s